name: Check Links

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check for dead links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,204,301,302,308
            --exclude-path ./CHANGELOG.md
            --config .lychee.toml
            '**/*.md'
          fail: true
          debug: true
