# -*- coding: utf-8 -*-
"""
=============================================================================
TOKCER AI — 365 TEMA VIDEO KONTEN DATA REPOSITORY
=============================================================================
"""

TEMA_365 = [
    # ─────────────────────────────────────────────────────────
    # 🔥 PILAR 1 — PAIN POINT & AWARENESS (Hari 1–40)
    # Target: Seller yang belum tahu ada solusinya
    # ─────────────────────────────────────────────────────────
    "Kenapa omzet naik tapi tabungan tetap tipis? Ini penyebabnya",
    "Seller Shopee wajib tahu: 3 kebocoran profit yang sering tidak disadari",
    "Harga sudah murah, tapi masih kalah saing — salah di mana?",
    "Buka lapak dari pagi sampai malam, tapi margin cuma 3%",
    "Kesalahan paling umum seller baru saat ngitung HPP produk",
    "Kenapa promo flash sale malah bikin rugi? Ini faktanya",
    "Tanda-tanda toko kamu sedang dalam mode autopilot RUGI",
    "Seller dengan 500 order/bulan tapi nggak bisa gaji karyawan — kenapa?",
    "Mitos vs fakta: 'Yang penting omzet besar dulu baru mikir profit'",
    "3 jenis biaya tersembunyi di Shopee yang sering dilupakan seller",
    "Kenapa seller TikTok Shop banyak yang bakar uang tanpa sadar",
    "Stok numpuk = uang mati: cara seller cerdas menghindarinya",
    "Ongkir vs margin: siapa yang sering memakan profit kamu?",
    "Fenomena 'seller sibuk tapi miskin' — dan cara keluarnya",
    "Kapan waktu yang tepat seller harus mulai pakai tools otomasi?",
    "Jual 1.000 produk tapi profit bersih cuma Rp 500k — ini realitanya",
    "Kenapa seller yang jualannya 'biasa saja' justru lebih untung?",
    "Perbedaan omzet dan profit yang sering bikin seller galau",
    "Return produk bisa menggerus 20% profit kamu — begini cara proteksinya",
    "Seller yang baru naik level: tantangan yang tidak diajarkan di mana-mana",
    "Mengapa banyak toko Shopee gagal setelah 6 bulan pertama?",
    "Biaya iklan vs biaya operasional: mana yang lebih sering membunuh margin?",
    "Seller musiman vs seller konsisten: siapa yang lebih survive?",
    "Kenapa diskon besar tidak selalu menarik buyer yang loyal",
    "Tanda-tanda kamu sudah butuh dashboard bisnis, bukan cuma Excel",
    "Jebakan promo bundle yang justru menurunkan profit rata-rata",
    "Seller dengan 1 SKU vs 100 SKU: mana yang lebih mudah dikontrol?",
    "Kenapa seller sering underpricing produk premium mereka sendiri",
    "Analisis sederhana: berapa sebenarnya biaya per order kamu?",
    "Seller yang sudah setahun jualan tapi belum punya sistem — ini risikonya",
    "Perbandingan realita vs ekspektasi seller marketplace tahun pertama",
    "Kenapa compounding error kecil bisa jadi bencana keuangan toko besar",
    "Platform mana yang margin-nya paling 'ramah' untuk seller Indonesia?",
    "Seller yang nggak tahu cost structure-nya sendiri — survei mengejutkan",
    "Pengaruh rating toko terhadap biaya akuisisi customer baru",
    "Kapan seller harus berhenti jual produk yang 'laris' tapi tidak untung?",
    "Realita seller yang menjalankan 3 toko sekaligus tanpa sistem",
    "Mengapa pengelolaan cash flow lebih penting dari omzet bagi UMKM",
    "5 pertanyaan yang wajib bisa dijawab setiap seller tentang tokonya sendiri",
    "Seller yang 'merasa untung' vs seller yang 'tahu pasti untung' — bedanya jauh",

    # ─────────────────────────────────────────────────────────
    # 💡 PILAR 2 — EDUKASI HPP & MARGIN (Hari 41–80)
    # Target: Seller yang mau belajar cara hitung yang benar
    # ─────────────────────────────────────────────────────────
    "Tutorial: cara hitung HPP produk dari nol sampai jadi harga jual",
    "Rumus margin profit yang wajib dihapal setiap seller marketplace",
    "Bedanya gross margin vs net margin — mana yang lebih penting dipantau?",
    "Cara memasukkan biaya iklan ke dalam kalkulasi HPP dengan benar",
    "Langkah-langkah menghitung break-even point toko online kamu",
    "Cara set harga produk supaya tetap kompetitif tapi margin terjaga",
    "Tutorial: identifikasi produk mana yang paling untungkan toko kamu",
    "Cara kalkulasi ongkos packing yang sering dilupakan seller",
    "Pengaruh volume order terhadap HPP — economies of scale untuk UMKM",
    "Cara hitung biaya platform fee Shopee dan TikTok Shop secara akurat",
    "Tutorial analisis profitabilitas SKU: produk mana yang harus ditinggalkan?",
    "Cara memasukkan biaya gaji dan operasional ke dalam harga jual",
    "Strategi pricing produk bundling agar margin tidak tergerus",
    "Cara hitung ROI kampanye iklan Shopee Ads dan TikTok Ads",
    "Tutorial: buat laporan laba rugi sederhana untuk toko online",
    "Kenapa harga supplier naik 5% bisa bikin margin turun 15%",
    "Cara proteksi margin saat biaya logistik melonjak mendadak",
    "Tutorial: analisis biaya per kategori produk di toko kamu",
    "Cara membuat simulasi pricing sebelum launch produk baru",
    "Strategi negosiasi supplier agar HPP turun minimal 10%",
    "Cara hitung profit real setelah semua biaya return dan refund",
    "Tutorial: mapping semua cost center di toko online kamu",
    "Cara pakai prinsip 80/20 untuk fokus pada SKU paling profitable",
    "Strategi dynamic pricing: kapan menaikkan harga tanpa kehilangan buyer",
    "Cara set minimum order value agar setiap transaksi selalu untung",
    "Tutorial: audit toko bulanan yang bisa dilakukan dalam 30 menit",
    "Cara hitung biaya customer acquisition untuk toko marketplace",
    "Strategi penetapan harga untuk produk dengan kompetitor banyak",
    "Tutorial: pahami laporan keuangan Shopee/TikTok yang sering diabaikan",
    "Cara identifikasi 'produk zombie' — laris tapi diam-diam menyedot margin",
    "Tutorial: buat sistem peringatan dini ketika margin produk drop",
    "Cara analisis tren harga kompetitor tanpa tools mahal",
    "Strategi repricing otomatis agar tidak terus-terusan monitor manual",
    "Tutorial lengkap: dari harga beli supplier ke harga jual akhir",
    "Cara membedakan biaya tetap vs biaya variabel di toko online",
    "Strategi pengelolaan multiple SKU agar tidak kelabakan soal margin",
    "Tutorial: kenali indikator keuangan toko yang wajib dipantau mingguan",
    "Cara optimasi profit dari produk lama yang sudah turun ordernya",
    "Strategi upsell dan cross-sell yang terbukti meningkatkan rata-rata margin",
    "Tutorial: rekonsiliasi keuangan toko marketplace end-of-month",

    # ─────────────────────────────────────────────────────────
    # 🤖 PILAR 3 — OTOMASI & AI FOR SELLER (Hari 81–120)
    # Target: Seller yang ingin efisiensi tanpa coding
    # ─────────────────────────────────────────────────────────
    "Apa itu otomasi toko online dan kenapa seller UMKM butuh ini sekarang",
    "5 tugas repetitif di toko online yang bisa langsung diotomasi hari ini",
    "Cara pakai AI untuk bikin deskripsi produk yang convert — tanpa nulis sendiri",
    "Tutorial: otomasi laporan harian toko dengan tools gratis",
    "Kenapa seller yang pakai AI lebih cepat scale-up dibanding yang manual",
    "Cara buat sistem notifikasi otomatis ketika stok produk mau habis",
    "Otomasi balasan pertanyaan buyer yang paling sering ditanya",
    "Tutorial: sinkronisasi stok multi-platform tanpa input manual",
    "Cara AI membantu seller prediksi produk mana yang akan trending",
    "Otomasi pengiriman laporan profit ke WhatsApp setiap hari",
    "Tutorial: pakai Make.com untuk automasi alur kerja toko tanpa coding",
    "Cara membuat dashboard monitor toko yang update otomatis",
    "AI untuk analisis review produk: cara tahu apa yang benar-benar diinginkan buyer",
    "Otomasi follow-up order: cara tingkatkan repeat buyer secara autopilot",
    "Tutorial: buat bot WhatsApp sederhana untuk CS toko online",
    "Cara AI mengoptimasi jadwal posting konten toko otomatis",
    "Otomasi kalkulasi komisi reseller/affiliate tanpa spreadsheet manual",
    "Tutorial: gunakan Google Sheets + AI untuk dashboard toko gratis",
    "Cara pakai AI untuk A/B testing foto produk secara cerdas",
    "Otomasi analisis kompetitor: pantau harga rival tanpa capek scroll",
    "Tutorial: workflow otomasi untuk toko dengan 500+ SKU",
    "Cara AI membantu forecast kebutuhan stok bulan depan",
    "Otomasi pembuatan konten promo harian: dari prompt ke caption siap posting",
    "Tutorial: integrasi Tokcer AI dengan sistem toko yang sudah ada",
    "Cara membuat SOP digital toko yang bisa dijalankan tim tanpa supervisi",
    "AI untuk segmentasi buyer: kirim promosi yang tepat ke orang yang tepat",
    "Tutorial: otomasi rekap performa iklan Shopee Ads setiap malam",
    "Cara AI membantu seller menulis judul produk yang SEO-friendly",
    "Otomasi pengajuan komplain seller ke Shopee/TikTok — hemat waktu berjam-jam",
    "Tutorial: buat sistem reward otomatis untuk pelanggan setia",
    "Cara AI menganalisis tren pasar dan memberikan rekomendasi aksi",
    "Otomasi pembuatan invoice dan bukti pengiriman massal",
    "Tutorial: pakai AI untuk respon review negatif yang profesional",
    "Cara bangun 'toko autopilot' yang bisa jalan tanpa kamu monitor 24 jam",
    "Otomasi pengelolaan voucher dan diskon berdasarkan stok real-time",
    "Tutorial: AI assistant untuk briefing harian tim operasional toko",
    "Cara AI mengidentifikasi waktu terbaik untuk launch kampanye promo",
    "Otomasi backup data toko harian — proteksi dari kehilangan data",
    "Tutorial: dari transkrip meeting ke SOP toko dalam 10 menit pakai AI",
    "Cara membangun ekosistem otomasi toko yang scalable dari nol",

    # ─────────────────────────────────────────────────────────
    # 🏮 PILAR 4 — TOKCER AI PRODUCT SHOWCASE (Hari 121–160)
    # Target: Awareness & konversi langsung ke platform
    # ─────────────────────────────────────────────────────────
    "Demo live: begini tampilan Dashboard Tokcer AI untuk seller Shopee",
    "Fitur Kalkulator HPP Tokcer AI: hitung profit 1 klik, bukan 1 jam",
    "Cara Tokcer AI membantu seller tahu untung-rugi secara real-time",
    "Demo: Compare SKU Tokcer AI — produk mana yang paling layak diperjuangkan",
    "Paket Nyala Tokcer AI: gratis tapi powerful — ini yang bisa kamu dapat",
    "Kenapa 500+ seller UMKM pilih Tokcer AI untuk kelola bisnis mereka",
    "Fitur baru Tokcer AI: [placeholder — isi sesuai rilis fitur terbaru]",
    "Perbandingan sebelum vs sesudah pakai Tokcer AI — data nyata dari user",
    "Tutorial: cara daftar dan setup akun Tokcer AI dalam 5 menit",
    "Demo: laporan margin otomatis Tokcer AI untuk TikTok Shop seller",
    "Paket Terbang Tokcer AI: 30 hari content hub untuk seller yang mau scale",
    "Cara seller Surabaya meningkatkan profitnya 30% pakai Tokcer AI",
    "Fitur AEO Engine Tokcer AI: konten blog toko yang dibuat AI dalam detik",
    "Demo lengkap: workflow satu hari seller yang pakai Tokcer AI",
    "Studi kasus: seller fashion Bandung dari chaos ke sistem pakai Tokcer AI",
    "Paket Autopilot Tokcer AI: Make + WA API = toko yang benar-benar otomatis",
    "Cara Tokcer AI membantu seller multi-platform kelola semua dari 1 dashboard",
    "Demo: fitur notifikasi WhatsApp otomatis dari Tokcer AI",
    "User review: 'Tokcer AI mengubah cara saya lihat bisnis saya sendiri'",
    "Fitur Visibility Score Tokcer AI: pantau seberapa sering brand kamu disebut AI",
    "Cara update terbaru Tokcer AI membuat analisis produk makin akurat",
    "Demo: seller kuliner Makassar pakai Tokcer AI untuk rekap harian",
    "Paket Orbit Tokcer AI: layanan Done-For-You untuk seller yang sudah scale",
    "Behind the scenes: bagaimana tim Tokcer AI membangun fitur baru",
    "Demo: integrasi Tokcer AI dengan Shopee seller center",
    "Tokcer AI vs spreadsheet manual — perbandingan yang menyakitkan",
    "Cara seller TikTok Shop pakai Tokcer AI untuk analisis konten viral",
    "Demo: fitur bulk SKU analysis di Tokcer AI untuk seller dengan ratusan produk",
    "Roadmap Tokcer AI 2026: fitur apa saja yang akan hadir?",
    "Tutorial: cara maksimalkan paket Nyala (gratis) Tokcer AI dari hari pertama",
    "Studi kasus: seller elektronik Jakarta naik kelas pakai Tokcer AI",
    "Demo: cara Tokcer AI generate deskripsi produk SEO-friendly otomatis",
    "Cara Tokcer AI membantu tim kecil bekerja seperti tim besar",
    "Feature spotlight: dashboard real-time Tokcer AI yang bisa diakses dari HP",
    "Demo: seller kosmetik Yogyakarta kelola 200 SKU pakai Tokcer AI",
    "Kenapa Tokcer AI lebih cocok untuk seller Indonesia dibanding tools luar",
    "Tutorial: setup alert margin di Tokcer AI — jangan sampai terlambat tahu rugi",
    "Studi kasus: seller Tokopedia scale up ke TikTok Shop dengan bantuan Tokcer AI",
    "Demo: fitur rekap bulanan otomatis Tokcer AI — laporan siap dalam 1 detik",
    "Tokcer AI: dari tools ke partner bisnis seller Indonesia",

    # ─────────────────────────────────────────────────────────
    # 📈 PILAR 5 — STRATEGI SCALE-UP MARKETPLACE (Hari 161–200)
    # Target: Seller yang sudah jalan dan mau naik level
    # ─────────────────────────────────────────────────────────
    "Strategi naik dari 100 ke 1.000 order per bulan tanpa tambah tim besar",
    "Cara seller Shopee masuk Star Seller tanpa bakar budget iklan berlebihan",
    "Strategi ekspansi dari 1 platform ke multi-platform yang terbukti works",
    "Cara membangun brand toko yang membuat buyer balik lagi tanpa promo",
    "Strategi portfolio SKU: kapan harus fokus, kapan harus diversifikasi",
    "Cara scale toko dengan modal terbatas: prioritas yang sering salah",
    "Strategi content marketing untuk seller yang tidak punya waktu buat konten",
    "Cara seller kecil bisa menang melawan seller besar di halaman pencarian",
    "Strategi membangun review positif organik yang mempercepat penjualan",
    "Cara optimasi toko untuk algoritma Shopee terbaru",
    "Strategi TikTok Shop: dari 0 ke toko yang recommend-able oleh FYP",
    "Cara seller menggunakan data historis untuk keputusan stok yang cerdas",
    "Strategi bundling produk yang meningkatkan average order value 2x lipat",
    "Cara membangun loyalitas buyer di era marketplace yang penuh kompetitor",
    "Strategi seasonal: cara maksimalkan 11.11, 12.12, dan Harbolnas",
    "Cara seller B2B masuk ke channel marketplace consumer tanpa konflik",
    "Strategi membangun ekosistem reseller yang tidak memakan margin utama",
    "Cara memanfaatkan fitur live streaming Shopee/TikTok untuk konversi tinggi",
    "Strategi pengelolaan iklan berbayar agar ROAS selalu positif",
    "Cara seller memanfaatkan voucher platform tanpa merusak struktur harga",
    "Strategi ekspansi ke luar Jawa: kota mana yang paling potensial?",
    "Cara seller kuliner/FnB menembus marketplace dengan tantangan khusus mereka",
    "Strategi build-up toko baru dalam 90 hari pertama yang terbukti efektif",
    "Cara seller pakaian survive di industri dengan return rate tinggi",
    "Strategi partnership dengan seller lain untuk saling memperkuat jaringan",
    "Cara memanfaatkan program affiliate marketplace tanpa biaya tambahan besar",
    "Strategi video produk singkat yang terbukti boost konversi di TikTok",
    "Cara seller merespons perubahan algoritma platform tanpa panik",
    "Strategi membangun toko dengan recurring revenue dari pelanggan tetap",
    "Cara seller handicraft/kerajinan bersaing di marketplace yang price-sensitive",
    "Strategi penetrasi pasar kota tier-2 dan tier-3 yang belum jenuh",
    "Cara seller mengelola ekspektasi buyer untuk meminimalkan komplain",
    "Strategi konten edukatif produk yang membangun trust sebelum purchase",
    "Cara seller elektronik mengelola garansi dan return secara efisien",
    "Strategi co-selling dengan brand atau influencer untuk boost visibilitas",
    "Cara seller kosmetik lokal membangun kepercayaan di tengah maraknya produk palsu",
    "Strategi maximizing profit dari peak season tanpa over-stock",
    "Cara seller menggunakan data kompetitor untuk keputusan strategis",
    "Strategi konversi dari toko online ke ekosistem bisnis yang lebih mandiri",
    "Cara seller UMKM mempersiapkan diri masuk ke pasar ekspor ASEAN",

    # ─────────────────────────────────────────────────────────
    # 💬 PILAR 6 — MINDSET & MOTIVASI SELLER (Hari 201–230)
    # Target: Engagement, shares, dan emotional connection
    # ─────────────────────────────────────────────────────────
    "Seller yang gagal bukan karena kekurangan modal — tapi karena ini",
    "Mindset yang harus berubah ketika toko kamu mulai scale-up",
    "Jujur soal omzet vs profit: pelajaran keras yang bikin seller tumbuh",
    "Kenapa seller terbaik tidak pernah berhenti belajar meski sudah sukses",
    "Dari Rp 5 juta ke Rp 50 juta/bulan: perjalanan seller yang tidak linear",
    "Hal yang tidak diajarkan di kelas bisnis tapi selalu dihadapi seller",
    "Kenapa kesabaran adalah 'tools' paling underrated untuk seller UMKM",
    "Realita brutal: seller yang sukses vs seller yang sekedar survive",
    "Cara mengambil keputusan bisnis ketika data tidak lengkap",
    "Kenapa seller yang fokus pada sistem lebih unggul dari yang fokus pada trik",
    "Pelajaran dari seller yang pernah hampir bangkrut tapi berhasil balik",
    "Cara mengelola stress sebagai owner toko online tanpa support team",
    "Kenapa 'done is better than perfect' berlaku juga untuk seller marketplace",
    "Seller yang terlalu sibuk untuk belajar — dan akibatnya",
    "Cara memisahkan emosi dari keputusan bisnis saat kondisi sulit",
    "Perbedaan seller yang menyerah di bulan ke-3 vs yang survive sampai tahun ke-2",
    "Kenapa komunitas seller bisa jadi aset bisnis yang sering diremehkan",
    "Cara seller mengukur progres yang sebenarnya — bukan cuma dari omzet",
    "Mindset abundance vs scarcity di dunia marketplace yang kompetitif",
    "Pesan untuk seller yang baru mulai: jangan percaya semua yang viral",
    "Cara membangun kepercayaan diri seller yang baru pertama kali loss besar",
    "Kenapa data adalah 'bahasa cinta' seller kepada bisnis mereka sendiri",
    "Seller yang tidak mau diukur — dan mengapa itu bahaya",
    "Cara menemukan 'why' bisnis yang membuat seller bertahan di masa sulit",
    "Mindset tentang kompetitor: ancaman atau cermin yang membuatmu lebih baik?",
    "Kenapa seller yang berfokus pada value lebih tahan banting dari yang berfokus harga",
    "Cara seller membangun mental 'sistem dulu, hasil kemudian'",
    "Realita seller yang berhasil: tidak ada jalan pintas, ada jalan yang lebih cerdas",
    "Kenapa transparansi keuangan kepada diri sendiri adalah langkah awal kemajuan",
    "Pesan dari Tokcer AI untuk setiap seller Indonesia yang sedang berjuang",

    # ─────────────────────────────────────────────────────────
    # 🎯 PILAR 7 — TIPS & TRIK PLATFORM SPESIFIK (Hari 231–260)
    # Target: Tutorial taktis yang shareable
    # ─────────────────────────────────────────────────────────
    "Tips Shopee: cara naik di halaman pencarian tanpa naikkan biaya iklan",
    "Trik TikTok Shop: format video yang paling banyak trigger pembelian impulsif",
    "Cara optimasi foto produk Shopee yang terbukti meningkatkan CTR",
    "Tips: waktu terbaik upload produk baru di Shopee berdasarkan data",
    "Trik konten TikTok: hook 3 detik yang membuat orang berhenti scroll",
    "Tips Shopee: cara set voucher toko yang menguntungkan, bukan merugikan",
    "Cara mengelola toko Shopee dari HP tanpa kehilangan produktivitas",
    "Trik TikTok: cara gunakan trending audio untuk konten produk tanpa cringe",
    "Tips: cara membuat judul produk Shopee yang muncul di pencarian AI",
    "Trik live TikTok Shop: setup minimal yang bisa langsung closing",
    "Tips Shopee: cara handle komplain pembeli agar tidak kena penalti",
    "Cara riset produk potensial di TikTok Shop sebelum invest stok",
    "Tips: pengaturan ongkir Shopee yang optimal untuk margin dan konversi",
    "Trik konten: cara seller biasa bisa viral di FYP TikTok",
    "Tips Shopee: strategi iklan Shopee Ads dengan budget di bawah Rp 50ribu/hari",
    "Cara pakai fitur Shopee Live untuk seller yang belum pernah siaran",
    "Trik TikTok: cara buat konten tutorial produk yang edukasi sekaligus jualan",
    "Tips: cara membuat thumbnail video TikTok yang klik-magnetik",
    "Strategi komentar produk Shopee: cara organik dapat review bintang 5",
    "Trik cara pakai fitur bundling di Shopee untuk naikan average order",
    "Tips: cara memanfaatkan program Gratis Ongkir Shopee tanpa tekor",
    "Cara seller kosmetik buat konten before-after yang convert di TikTok",
    "Tips: pengaturan stok aman di Shopee untuk hindari penalty kehabisan",
    "Trik: cara membuat highlight Shopee/TikTok yang bikin orang mau DM",
    "Tips laporan Shopee: data apa saja yang wajib dianalisis setiap minggu",
    "Cara buat konten 'unboxing by seller' yang membangun kepercayaan buyer",
    "Tips: cara optimasi bio toko Shopee agar terlihat profesional",
    "Trik: cara respond negatif review Shopee yang justru menarik buyer baru",
    "Tips: cara seller makanan pakai fitur COD Shopee tanpa risiko besar",
    "Cara seller craft/handmade membangun narasi produk yang premium di TikTok",

    # ─────────────────────────────────────────────────────────
    # 📊 PILAR 8 — DATA & ANALITIK UNTUK SELLER (Hari 261–285)
    # Target: Seller yang mau lebih data-driven
    # ─────────────────────────────────────────────────────────
    "Cara baca laporan penjualan Shopee yang selama ini kamu abaikan",
    "3 metrik toko online yang lebih penting dari sekadar total omzet",
    "Cara menggunakan data review untuk perbaikan produk yang nyata",
    "Tutorial: buat KPI sederhana untuk toko online yang bisa dicek harian",
    "Cara analisis tren penjualan untuk prediksi bulan depan",
    "Data apa yang harus dikumpulkan seller sejak hari pertama buka toko",
    "Cara pakai cohort analysis sederhana untuk toko UMKM",
    "Tutorial: rekap performa iklan mingguan dalam 10 menit",
    "Cara identifikasi buyer segmen mana yang paling profitable",
    "Analitik sederhana: cara tahu produk mana yang layak di-restock massal",
    "Cara menghitung customer lifetime value untuk toko marketplace",
    "Tutorial: buat laporan keuangan toko bulanan yang tidak butuh akuntan",
    "Cara analisis data kompetitor menggunakan fitur Shopee yang tersedia gratis",
    "Metrik konten TikTok yang benar-benar berhubungan dengan revenue toko",
    "Cara pakai Google Trends untuk riset produk musiman marketplace",
    "Tutorial: dashboard sederhana untuk pantau kesehatan toko dari 1 halaman",
    "Cara analisis data return untuk identifikasi masalah produk sebelum membesar",
    "Metrik iklan: bedanya CTR, CVR, dan ROAS — dan mana yang paling penting",
    "Cara membaca grafik tren Shopee Insight untuk keputusan stok",
    "Tutorial: analisis profitabilitas per channel penjualan",
    "Cara pakai data untuk justifikasi kenaikan harga kepada buyer",
    "Analitik konten: cara tahu jenis video mana yang paling drive transaksi",
    "Tutorial: rekonsiliasi penjualan Shopee vs stok gudang secara berkala",
    "Cara membangun 'early warning system' keuangan toko dari data sederhana",
    "Data seller terbaik Indonesia — benchmark yang bisa kamu kejar",

    # ─────────────────────────────────────────────────────────
    # 🌟 PILAR 9 — STUDI KASUS & CERITA SUKSES (Hari 286–310)
    # Target: Social proof dan inspirasi nyata
    # ─────────────────────────────────────────────────────────
    "Studi kasus: seller fashion Bandung dari Rp 8 juta ke Rp 80 juta/bulan",
    "Kisah nyata: seller makanan Surabaya yang hampir tutup sebelum temukan sistemnya",
    "Bagaimana seller elektronik Jakarta memangkas biaya operasional 40% dalam 3 bulan",
    "Studi kasus: seller kosmetik lokal yang berhasil kalahkan brand besar di Shopee",
    "Kisah seller ibu rumah tangga Medan yang scale-up bisnis sampannya tanpa utang",
    "Bagaimana seller furniture Semarang build community yang loyal dan profitable",
    "Studi kasus: toko dropship yang berhasil transisi jadi seller stok mandiri",
    "Kisah seller Tokopedia yang ekspansi ke TikTok Shop dan 3x lipatkan omzetnya",
    "Bagaimana seller kaos polos bertahan di pasar paling kompetitif marketplace",
    "Studi kasus: seller UMKM yang berhasil masuk program Shopee Mall",
    "Kisah seller makanan beku Yogyakarta yang pakai sistem untuk scale ke luar Jawa",
    "Bagaimana seller perlengkapan bayi memanfaatkan komunitas ibu untuk viral organik",
    "Studi kasus: reseller yang build brand sendiri dalam 12 bulan",
    "Kisah seller yang pernah rugi Rp 30 juta dalam sebulan — dan pelajarannya",
    "Bagaimana seller craft menemukan niche yang tidak ada kompetitornya",
    "Studi kasus: toko yang berhasil survive dan tumbuh saat pandemi e-commerce slow",
    "Kisah seller Makassar yang build tim dari 1 orang ke 8 orang dalam setahun",
    "Bagaimana seller agrikultur masuk marketplace dan buka pasar baru",
    "Studi kasus: seller yang berhasil naik ke tier Autopilot dengan Tokcer AI",
    "Kisah nyata: seller yang akhirnya bisa gaji diri sendiri dari toko online",
    "Bagaimana seller buku dan alat tulis menemukan posisi unik di marketplace",
    "Studi kasus: seller herbal lokal yang build trust dan konversi premium",
    "Kisah seller yang mengubah hobi menjadi bisnis marketplace yang sustainable",
    "Bagaimana seller apparel anak survive di pasar musiman dengan sistem yang tepat",
    "Studi kasus: seller yang berhasil automate 80% operasional tokonya",

    # ─────────────────────────────────────────────────────────
    # 🔮 PILAR 10 — TREN & MASA DEPAN E-COMMERCE (Hari 311–330)
    # Target: Thought leadership dan brand authority
    # ─────────────────────────────────────────────────────────
    "Tren marketplace Indonesia 2026: apa yang berubah dan apa yang tetap",
    "Masa depan TikTok Shop di Indonesia — prediksi dan implikasinya untuk seller",
    "AI commerce: bagaimana kecerdasan buatan mengubah cara orang belanja online",
    "Tren: mengapa seller yang pakai data AI akan meninggalkan yang manual jauh di belakang",
    "Masa depan SEO untuk toko online: persiapan untuk era pencarian AI",
    "Tren social commerce: belanja dari konten, bukan dari toko — apa artinya untuk seller?",
    "Prediksi: bagaimana platform marketplace mana yang akan dominan di Indonesia 2027",
    "AI vs seller manusia: kolaborasi seperti apa yang paling menguntungkan?",
    "Tren micro-fulfillment: gudang kecil di kota lokal yang mengubah logistik",
    "Masa depan live commerce di Indonesia — potensi yang belum dimanfaatkan maksimal",
    "Tren: seller yang memiliki data first-party akan lebih powerful dari yang tidak",
    "Prediksi: bagaimana pembayaran digital akan terus reshape e-commerce Indonesia",
    "Tren konten shoppable: dari video ke checkout dalam 1 tap",
    "Masa depan program loyalitas untuk toko marketplace independent",
    "Tren sustainability: seller yang eco-friendly makin disukai — peluang atau beban?",
    "Prediksi: peran AI assistant dalam keputusan pembelian konsumen Indonesia",
    "Tren: personalisasi di scale — bagaimana AI membuat setiap buyer merasa spesial",
    "Masa depan UMKM digital Indonesia — optimisme yang berbasis data",
    "Tren cross-border commerce ASEAN: peluang untuk seller Indonesia go-regional",
    "Prediksi: peran AI assistant dalam keputusan pembelian konsumen Indonesia",

    # ─────────────────────────────────────────────────────────
    # ❓ PILAR 11 — FAQ & MYTH BUSTING (Hari 331–350)
    # Target: Engagement dan menghilangkan keberatan prospek
    # ─────────────────────────────────────────────────────────
    "Mitos: 'Platform gratis sudah cukup, tidak perlu tools berbayar' — ini faktanya",
    "FAQ: Apakah seller baru perlu tools manajemen atau tunggu omzet dulu?",
    "Mitos: 'Otomasi toko hanya untuk seller besar' — fakta yang membalik asumsi",
    "FAQ: Berapa budget minimum untuk mulai beriklan di Shopee dan TikTok?",
    "Mitos: 'Jual murah = pasti laris' — kenapa strategi ini sering backfire",
    "FAQ: Apakah Tokcer AI bisa dipakai seller yang tidak bisa coding sama sekali?",
    "Mitos: 'Toko online tidak butuh laporan keuangan formal' — risikonya nyata",
    "FAQ: Berapa lama biasanya toko online mulai balik modal dari iklan?",
    "Mitos: 'Semakin banyak SKU semakin besar omzet' — data bilang sebaliknya",
    "FAQ: Bagaimana cara migrasi dari spreadsheet manual ke tools otomasi?",
    "Mitos: 'Viral di TikTok pasti bikin toko laris' — kondisi yang sering diabaikan",
    "FAQ: Apakah pakai AI untuk konten toko melanggar kebijakan marketplace?",
    "Mitos: 'Review jelek = toko mati' — cara mengubah krisis jadi peluang",
    "FAQ: Kapan waktu terbaik untuk upgrade paket Tokcer AI?",
    "Mitos: 'Seller yang sudah profit tidak perlu belajar hal baru' — bahayanya nyata",
    "FAQ: Apakah Tokcer AI support untuk seller Tokopedia selain Shopee dan TikTok?",
    "Mitos: 'Harga lebih tinggi selalu menurunkan penjualan' — contoh kasus yang berbicara",
    "FAQ: Bagaimana cara backup data toko jika platform mengalami gangguan?",
    "Mitos: 'Affiliate/reseller selalu menggerus margin' — jika dikelola dengan benar",
    "FAQ: Fitur apa di Tokcer AI yang paling cepat memberikan dampak nyata?",

    # ─────────────────────────────────────────────────────────
    # 🎬 PILAR 12 — KONTEN INTERAKTIF & KOMUNITAS (Hari 351–365)
    # Target: Engagement tinggi, UGC, dan komunitas Tokcer AI
    # ─────────────────────────────────────────────────────────
    "Challenge: hitung profit real toko kamu sekarang dan share hasilnya",
    "Poll: tools apa yang paling kamu butuhkan sebagai seller sekarang?",
    "Q&A: tanya apa saja tentang margin and profit — jawab live bersama Tokcer AI",
    "Community spotlight: seller terbaik bulan ini pengguna Tokcer AI",
    "Challenge: 7 hari optimasi toko pakai Tokcer AI — siapa mau ikut?",
    "Diskusi: masalah seller nomor 1 yang paling ingin diselesaikan saat ini",
    "Feedback session: fitur Tokcer AI apa yang paling membantu kamu?",
    "Compilation: tips terbaik dari komunitas seller Tokcer AI bulan ini",
    "Behind the scenes: proses Tokcer AI membangun fitur baru bersama seller",
    "Community challenge: foto setup toko/workspace seller paling kreatif",
    "Milestone celebration: terima kasih 1.000 seller aktif Tokcer AI!",
    "Recap tahunan: pelajaran terbesar dari 365 hari konten Tokcer AI",
    "Preview: apa yang akan hadir di Tokcer AI tahun depan",
    "Surat terbuka dari Tokcer AI: komitmen kami untuk seller UMKM Indonesia",
    "Closing: 365 hari dari prompt ke profit — perjalanan yang baru dimulai",
]

PILARS = {
    "Pilar 1 — Pain Point & Awareness":       list(range(0, 40)),
    "Pilar 2 — Edukasi HPP & Margin":          list(range(40, 80)),
    "Pilar 3 — Otomasi & AI for Seller":       list(range(80, 120)),
    "Pilar 4 — Tokcer AI Product Showcase":    list(range(120, 160)),
    "Pilar 5 — Strategi Scale-Up Marketplace": list(range(160, 200)),
    "Pilar 6 — Mindset & Motivasi Seller":     list(range(200, 230)),
    "Pilar 7 — Tips & Trik Platform Spesifik": list(range(230, 260)),
    "Pilar 8 — Data & Analitik untuk Seller":  list(range(260, 285)),
    "Pilar 9 — Studi Kasus & Cerita Sukses":   list(range(285, 310)),
    "Pilar 10 — Tren & Masa Depan E-Commerce": list(range(310, 330)),
    "Pilar 11 — FAQ & Myth Busting":           list(range(330, 350)),
    "Pilar 12 — Konten Interaktif & Komunitas":list(range(350, 365)),
}

def get_tema(hari_ke):
    idx = (hari_ke - 1) % len(TEMA_365)
    tema_text = TEMA_365[idx]
    pilar_name = next(
        (nama for nama, indices in PILARS.items() if idx in indices),
        "Pilar Lainnya"
    )
    return {
        "hari": hari_ke,
        "index": idx + 1,
        "tema": tema_text,
        "pilar": pilar_name,
    }
