"""Structured checkpoint template and path helpers.

Ported from MiMo-Code's session/checkpoint-templates.ts and checkpoint-paths.ts.
Provides 11-section checkpoint format with per-section token budgets.
"""

from dataclasses import dataclass
from pathlib import Path


@dataclass
class SectionBudget:
    """Token budget for a checkpoint section."""

    name: str
    budget: int


CHECKPOINT_TEMPLATE = """# Session checkpoint
_Generated by checkpoint writer; structure preserved across updates. Edit only content under italic instructions._

## §1 Active intent
_User's most recent explicit request, verbatim block-quoted from the conversation._

(none yet)

## §2 Next concrete action
_The single next concrete step, derived from §1 and current state._

(none yet)

## §3 Directives (this session)
_This session's specific working style. Project-level rules are in MEMORY.md — do not duplicate them here._

(none)

## §4 Task tree
_Hierarchical view of tasks with current focus marked._

(none yet)

## §5 Current work
_Description of what was being done immediately before this checkpoint. Mention specific file paths._

(none yet)

## §6 Files and code sections
_Files actively being read or modified. List with one-line purpose._

(none yet)

## §7 Discovered knowledge (cross-task)
_Facts learned during this session that may apply to future tasks._

(none yet)

## §8 Errors and fixes
_Errors encountered this session and how they were resolved. Newest first._

(none)

## §9 Live resources
_Runtime state: branch, uncommitted files, running processes, temp artifacts._

(none yet)

## §10 Design decisions and discussion outcomes
_Decisions reached through discussion that produced no immediate code artifact._

(none yet)

## §11 Open notes
_Catch-all for items that don't fit §1-§10._

(none yet)
"""

MEMORY_TEMPLATE = """# Project memory
_Durable project-level knowledge. Persists across all sessions._

## Project context
_What is this project? What's its goal?_

(none yet)

## Rules
_Hard constraints that every session must respect._

(none yet)

## Architecture decisions
_Major design choices with rationale._

(none yet)

## Discovered durable knowledge
_Cross-task facts that survive across sessions._

(none yet)
"""

NOTES_TEMPLATE = """# Session notes
_Free-form scratchpad for the main agent. Append entries as you go._
"""

# Section budgets for checkpoint.md (token estimates per section)
# Total ~11K tokens
CHECKPOINT_SECTION_BUDGETS: dict[str, int] = {
    "§1 Active intent": 500,
    "§2 Next concrete action": 1000,
    "§3 Directives (this session)": 800,
    "§4 Task tree": 1000,
    "§5 Current work": 2000,
    "§6 Files and code sections": 1500,
    "§7 Discovered knowledge (cross-task)": 2000,
    "§8 Errors and fixes": 1500,
    "§9 Live resources": 1000,
    "§10 Design decisions and discussion outcomes": 3000,
    "§11 Open notes": 800,
}

# Section budgets for MEMORY.md (project-level)
# Total ~10K tokens
MEMORY_SECTION_BUDGETS: dict[str, int] = {
    "Project context": 1000,
    "Rules": 2000,
    "Architecture decisions": 3000,
    "Discovered durable knowledge": 4000,
}


def meta_dir(session_id: str, data_dir: str | None = None) -> Path:
    """Get session memory root directory.

    Houses checkpoint artifacts, task narratives, and other per-session memory files.
    """
    if data_dir is None:
        import os

        xdg_data = os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))
        data_dir = str(Path(xdg_data) / "nanocode")
    return Path(data_dir) / "memory" / "sessions" / session_id


def checkpoint_path(session_id: str, data_dir: str | None = None) -> Path:
    """Get path to session checkpoint file."""
    return meta_dir(session_id, data_dir) / "checkpoint.md"


def memory_path(project_id: str = "default", data_dir: str | None = None) -> Path:
    """Get path to project memory file."""
    if data_dir is None:
        import os

        xdg_data = os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))
        data_dir = str(Path(xdg_data) / "nanocode")
    return Path(data_dir) / "memory" / "projects" / project_id / "MEMORY.md"


def global_memory_path(data_dir: str | None = None) -> Path:
    """Get path to global memory file."""
    if data_dir is None:
        import os

        xdg_data = os.environ.get("XDG_DATA_HOME", str(Path.home() / ".local" / "share"))
        data_dir = str(Path(xdg_data) / "nanocode")
    return Path(data_dir) / "memory" / "global" / "MEMORY.md"


def notes_path(session_id: str, data_dir: str | None = None) -> Path:
    """Get path to session notes file."""
    return meta_dir(session_id, data_dir) / "notes.md"


def tasks_dir(session_id: str, data_dir: str | None = None) -> Path:
    """Get path to session tasks directory."""
    return meta_dir(session_id, data_dir) / "tasks"


def progress_path(session_id: str, task_id: str, data_dir: str | None = None) -> Path:
    """Get path to per-task progress journal."""
    return tasks_dir(session_id, data_dir) / task_id / "progress.md"


def ensure_checkpoint_template(session_id: str, data_dir: str | None = None) -> Path:
    """Create checkpoint file from template if it doesn't exist.

    Returns path to the checkpoint file.
    """
    path = checkpoint_path(session_id, data_dir)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(CHECKPOINT_TEMPLATE)
    return path


def ensure_memory_template(
    project_id: str = "default", data_dir: str | None = None
) -> Path:
    """Create memory file from template if it doesn't exist.

    Returns path to the memory file.
    """
    path = memory_path(project_id, data_dir)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(MEMORY_TEMPLATE)
    return path


def ensure_notes_template(session_id: str, data_dir: str | None = None) -> Path:
    """Create notes file from template if it doesn't exist.

    Returns path to the notes file.
    """
    path = notes_path(session_id, data_dir)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(NOTES_TEMPLATE)
    return path
