#!/usr/bin/env python3
"""Verify that repository paths mentioned in the documentation exist.

Documentation rots when a file is renamed or removed and the prose that
pointed at it is not updated. This check reads the contributor- and
user-facing Markdown files, extracts every path they mention, and fails when
one of those paths is neither tracked in git nor present on disk.

What counts as a mention:

- A Markdown link target, resolved relative to the document that contains it
  (``[x](../examples/package-template)`` inside ``docs/`` points at
  ``examples/package-template``).
- A backtick code span holding a repository-relative path whose first segment
  is a known top-level directory or a tracked top-level file
  (``marmo_core/kernel.py``, ``.env.example``). Example filenames that belong
  to a user's own layout (``marmo-package.json``, ``SKILL.md``) are not
  repository paths and are skipped.
- A backtick code span holding a bare Python module name (``kernel.py``): it
  must match the basename of a tracked ``.py`` file somewhere in the tree.

URLs, anchors, and spans with wildcards or placeholders are skipped, as are
code spans with spaces (commands are not checked). Paths that are documented
on purpose although they are not tracked -- the local ``.env`` file, the
third-party skill corpus, generated caches -- are listed in
``UNTRACKED_BUT_DOCUMENTED`` with the reason.

Run it from anywhere:

    python3 scripts/check_doc_paths.py

The exit status is non-zero when a stale reference is found. The check is
dependency-free so CI can run it before installing anything.
"""

from __future__ import annotations

from fnmatch import fnmatchcase
from pathlib import Path, PurePosixPath
import posixpath
import re
import subprocess
import sys
from typing import Iterable, Iterator


ROOT = Path(__file__).resolve().parents[1]

# Documentation that is expected to describe the current repository layout.
# CHANGELOG.md is deliberately absent: it records history, so it legitimately
# names files that no longer exist. The planning notes at the repository root
# (要件定義書１.md, 改善策.md) describe intended or proposed work, not the tree.
DOC_GLOBS: tuple[str, ...] = (
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "AGENTS.md",
    "ARCHITECTURE.md",
    "docs/**/*.md",
    "benchmarks/README.md",
    ".github/**/*.md",
)

# Directories the documentation may always refer to. Listing them here means
# that deleting one of them makes every reference into it stale, instead of
# turning those references into unrecognised names that are skipped.
KNOWN_TOP_LEVEL: frozenset[str] = frozenset(
    {".github", "benchmarks", "docs", "examples", "marmo_core", "resources", "scripts", "tests", "tools"}
)

# Paths the documentation names although they are intentionally not tracked.
# An entry matches itself and everything below it; an entry containing ``*``
# is a glob over the whole path. Add the reason as a comment when extending it.
UNTRACKED_BUT_DOCUMENTED: dict[str, str] = {
    ".env": "local secrets, excluded by .gitignore",
    "resources/skills": "third-party skill corpus, not redistributable (see benchmarks/README.md)",
    "benchmarks/cache": "LLM reply cache written by the benchmark scripts on first run",
    "benchmarks/corpus/scale_corpus_*": "generated by benchmarks/generate_scale_corpus.py",
    "dist": "build output of python -m build",
    "skills": "output directory of tools/collect_skills.py",
}

_PATH_EXTENSIONS = (".md", ".py", ".json", ".jsonl", ".toml", ".yml", ".yaml", ".txt", ".in", ".example", ".lock")
_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")
_CODE_SPAN_RE = re.compile(r"`([^`\n]+)`")
_PLACEHOLDER_CHARS = ("*", "<", ">", "{", "}", "$", " ", "\t", "=", "|", ":", "\\")


def tracked_files(root: Path) -> set[str] | None:
    """Return the set of git-tracked paths, or None when git is unavailable."""

    try:
        completed = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"],
            capture_output=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if completed.returncode != 0:
        return None
    return {entry.decode("utf-8", "surrogateescape") for entry in completed.stdout.split(b"\0") if entry}


def _clean(candidate: str) -> str | None:
    """Strip anchors and decorations from a raw mention; None when it is not a path."""

    text = candidate.strip()
    if not text or "://" in text or text.startswith(("#", "mailto:")):
        return None
    text = text.split("#", 1)[0]
    if text.startswith("./"):
        text = text[2:]
    looks_like_path = "/" in text or text.endswith(_PATH_EXTENSIONS)
    text = text.rstrip("/")
    if not text or text.startswith("/") or not looks_like_path:
        return None
    if any(char in text for char in _PLACEHOLDER_CHARS):
        return None
    return text


def iter_mentions(markdown: str, document_dir: str = "") -> Iterator[str]:
    """Yield every repository-relative path a Markdown document mentions.

    ``document_dir`` is the document's directory relative to the repository
    root (``"docs"``, or ``""`` for a root-level file); link targets are
    resolved against it. Code spans are taken as written.
    """

    for match in _LINK_RE.finditer(markdown):
        cleaned = _clean(match.group(1))
        if cleaned is None:
            continue
        resolved = posixpath.normpath(posixpath.join(document_dir, cleaned))
        if resolved.startswith("..") or resolved == ".":
            continue
        yield resolved
    for match in _CODE_SPAN_RE.finditer(markdown):
        cleaned = _clean(match.group(1))
        if cleaned is not None:
            yield cleaned


def _top_level_entries(root: Path, tracked: set[str] | None) -> set[str]:
    if tracked is not None:
        return {path.split("/", 1)[0] for path in tracked}
    return {entry.name for entry in root.iterdir()}


def _exists(root: Path, path: str, tracked: set[str] | None) -> bool:
    if tracked is not None and (path in tracked or any(entry.startswith(path + "/") for entry in tracked)):
        return True
    return (root / path).exists()


def _documented_untracked(path: str) -> bool:
    for pattern in UNTRACKED_BUT_DOCUMENTED:
        if "*" in pattern:
            if fnmatchcase(path, pattern):
                return True
        elif path == pattern or path.startswith(pattern + "/"):
            return True
    return False


def _module_exists(root: Path, name: str, tracked: set[str] | None) -> bool:
    if tracked is not None:
        return any(PurePosixPath(entry).name == name for entry in tracked)
    return any(candidate.name == name for candidate in root.rglob("*.py"))


def find_stale_references(root: Path, documents: Iterable[Path], tracked: set[str] | None) -> list[tuple[Path, str]]:
    """Return ``(document, path)`` pairs whose path does not exist in the repository."""

    top_level = _top_level_entries(root, tracked) | KNOWN_TOP_LEVEL
    stale: list[tuple[Path, str]] = []
    for document in documents:
        markdown = document.read_text(encoding="utf-8")
        document_dir = document.resolve().relative_to(root.resolve()).parent.as_posix()
        seen: set[str] = set()
        for path in iter_mentions(markdown, "" if document_dir == "." else document_dir):
            if path in seen:
                continue
            seen.add(path)
            if _documented_untracked(path):
                continue
            if "/" not in path and path.endswith(".py"):
                if not _module_exists(root, path, tracked):
                    stale.append((document, path))
                continue
            if path.split("/", 1)[0] not in top_level:
                continue
            if not _exists(root, path, tracked):
                stale.append((document, path))
    return stale


def collect_documents(root: Path, patterns: Iterable[str] = DOC_GLOBS) -> list[Path]:
    documents: list[Path] = []
    for pattern in patterns:
        documents.extend(sorted(path for path in root.glob(pattern) if path.is_file()))
    return documents


def main() -> int:
    tracked = tracked_files(ROOT)
    documents = collect_documents(ROOT)
    stale = find_stale_references(ROOT, documents, tracked)
    if stale:
        print("stale path references found:", file=sys.stderr)
        for document, path in stale:
            print(f"  {document.relative_to(ROOT)}: {path}", file=sys.stderr)
        print(
            "Fix the reference, or add the path to UNTRACKED_BUT_DOCUMENTED in "
            "scripts/check_doc_paths.py with the reason it is not tracked.",
            file=sys.stderr,
        )
        return 1
    print(f"doc path check passed: {len(documents)} documents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
