"""Marmo-Core public API.

v1 covers the unified resource model, local resource loading, cross-kind
retrieval, rule-based set selection, and the CLI surface. On top of that,
the guarded execution loop (v2 preview) adds the Resource Activator, Tool and
Agent Runtimes, Context Compiler, mock LLM provider, and synchronous Kernel.
"""

from .adaptive import (
    CaseBasedRouter,
    CaseMember,
    RoutingCase,
    RoutingCaseStore,
    RoutingDecision,
    resolve_case,
)
from .activator import (
    Activation,
    BoundAgent,
    BoundTool,
    InjectedMemory,
    LoadedSkill,
    ResourceActivator,
)
from .agent_runtime import AgentResponse, AgentResult, AgentRuntime
from .audit import AuditLog, AuditRecord
from .compiler import AgentInterface, CompiledContext, CompiledSelectionContext, ContextCompiler
from .connectors import (
    Connector,
    ConnectorCircuitOpenError,
    ConnectorCommandError,
    ConnectorConfig,
    ConnectorError,
    ConnectorPathError,
    ConnectorRuntime,
    ConnectorTool,
    FileSystemConnector,
    HTTPConnector,
    SQLiteConnector,
    ShellConnector,
    connector_implementations,
    connector_resources,
    connector_tools,
    install_connectors,
)
from .evaluator import ExecutionEvaluator, ExecutionOutcome, outcomes_from_audit
from .errors import (
    ActivationError,
    MarmoError,
    PackageCompatibilityError,
    PackageError,
    PackageIntegrityError,
    ResourceLoadError,
    ResourceNotFoundError,
    ResourceValidationError,
    SecretResolutionError,
    ToolInputError,
)
from .hitl import (
    AutoApproveHitlBroker,
    CallbackHitlBroker,
    ConsoleHitlBroker,
    HitlBroker,
    HitlError,
    HitlPolicy,
    HitlRequest,
    HitlResponse,
    PendingHitlBroker,
)
from .kernel import Kernel, TaskResult
from .llm import (
    ChatMessage,
    LLMProvider,
    LLMResponse,
    LLMToolSpec,
    MockLLMProvider,
    ToolCall,
    estimate_tokens,
    tokenize,
)
from .graph_routing import CapabilityGraphRetriever
from .hierarchy import (
    EmbeddingClusterGrouping,
    GroupingStrategy,
    HierarchicalRetriever,
    NamespaceGrouping,
    PermissionGrouping,
    ProviderGrouping,
    RouteDecision,
)
from .llm_routing import HydeRetriever, LLMRerankRetriever, LLMSetSelector
from .loader import load_resource_definitions, load_registry
from .package import (
    KERNEL_VERSION,
    LOCK_FILENAME,
    MANIFEST_FILENAME,
    LocalResourcePackage,
    PackageDependency,
    PackageLock,
    PackageManifest,
    SemanticVersion,
    VersionRange,
    build_package_lock,
    discover_package_roots,
    read_package_manifest,
    verify_local_package,
    write_package_lock,
)
from .models import (
    ResourceDefinition,
    ResourceKind,
    ResourceMetadata,
    ResourceStats,
    SearchQuery,
    SearchResult,
    SelectedResourceSet,
    SelectionResult,
    ValidationIssue,
)
from .mcp import (
    MCPError,
    MCPStdioClient,
    MCPToolInfo,
    connect_mcp_server,
    mcp_tool_implementations,
    mcp_tool_resources,
)
from .planner import (
    LLMPlanner,
    Plan,
    PlanStep,
    Planner,
    RuleBasedPlanner,
    validate_plan,
)
from .policy import PolicyContext, PolicyDecision, PolicyGateway, PolicyRejectedError
from .providers import AnthropicLLMProvider, OpenAICompatibleLLMProvider
from .recovery import (
    CircuitBreaker,
    Failure,
    RecoveryDecision,
    RecoveryManager,
    RetryPolicy,
    compensation_for,
)
from .registry import ResourceRegistry
from .rerank import CrossEncoderProvider, CrossEncoderRerankRetriever
from .retriever import LexicalRetriever, Retriever
from .selector import (
    BranchAndBoundSetSelector,
    GreedyConstrainedSetSelector,
    RuleBasedSetSelector,
    SelectionContext,
    SetSelector,
    BeamSearchSetSelector,
)
from .semantic import (
    EmbeddingProvider,
    HashingEmbeddingProvider,
    HybridRetriever,
    OpenAICompatibleEmbeddingProvider,
)
from .safety import SafetyFinding, SafetyInspector
from .security import (
    CORE_ISOLATION_LEVELS,
    ISOLATION_LEVELS,
    PromptInjectionFinding,
    PromptInjectionInspector,
    label_untrusted_content,
)
from .secrets import (
    EnvironmentSecretResolver,
    MappingSecretResolver,
    SecretRef,
    SecretResolver,
)
from .state import (
    Checkpoint,
    InMemoryStateStore,
    JsonFileStateStore,
    SQLiteStateStore,
    StateConflictError,
    StateEvent,
    StateStore,
    TaskNotFoundError,
    TaskState,
)
from .tool_runtime import ToolResult, ToolRuntime, validate_arguments

__all__ = [
    "Activation",
    "ActivationError",
    "AgentResponse",
    "AgentResult",
    "AgentRuntime",
    "AgentInterface",
    "AnthropicLLMProvider",
    "AuditLog",
    "AuditRecord",
    "AutoApproveHitlBroker",
    "BeamSearchSetSelector",
    "BoundTool",
    "BoundAgent",
    "BranchAndBoundSetSelector",
    "CallbackHitlBroker",
    "CapabilityGraphRetriever",
    "CaseBasedRouter",
    "CaseMember",
    "ChatMessage",
    "Checkpoint",
    "CircuitBreaker",
    "CompiledContext",
    "CompiledSelectionContext",
    "ConsoleHitlBroker",
    "ContextCompiler",
    "Connector",
    "ConnectorCircuitOpenError",
    "ConnectorCommandError",
    "ConnectorConfig",
    "ConnectorError",
    "ConnectorPathError",
    "ConnectorRuntime",
    "ConnectorTool",
    "CORE_ISOLATION_LEVELS",
    "CrossEncoderProvider",
    "CrossEncoderRerankRetriever",
    "EmbeddingClusterGrouping",
    "EmbeddingProvider",
    "EnvironmentSecretResolver",
    "ExecutionEvaluator",
    "ExecutionOutcome",
    "Failure",
    "FileSystemConnector",
    "GreedyConstrainedSetSelector",
    "GroupingStrategy",
    "HashingEmbeddingProvider",
    "HierarchicalRetriever",
    "HitlBroker",
    "HitlError",
    "HitlPolicy",
    "HitlRequest",
    "HitlResponse",
    "HybridRetriever",
    "HydeRetriever",
    "HTTPConnector",
    "InMemoryStateStore",
    "ISOLATION_LEVELS",
    "InjectedMemory",
    "JsonFileStateStore",
    "Kernel",
    "LLMPlanner",
    "LLMProvider",
    "LLMRerankRetriever",
    "LLMResponse",
    "LLMSetSelector",
    "LLMToolSpec",
    "LexicalRetriever",
    "LoadedSkill",
    "MCPError",
    "MCPStdioClient",
    "MCPToolInfo",
    "MarmoError",
    "PackageCompatibilityError",
    "PackageDependency",
    "PackageError",
    "PackageIntegrityError",
    "PackageLock",
    "PackageManifest",
    "LocalResourcePackage",
    "KERNEL_VERSION",
    "LOCK_FILENAME",
    "MANIFEST_FILENAME",
    "MappingSecretResolver",
    "MockLLMProvider",
    "NamespaceGrouping",
    "OpenAICompatibleEmbeddingProvider",
    "OpenAICompatibleLLMProvider",
    "PendingHitlBroker",
    "PermissionGrouping",
    "Plan",
    "PlanStep",
    "Planner",
    "PolicyContext",
    "PolicyDecision",
    "PolicyGateway",
    "PolicyRejectedError",
    "PromptInjectionFinding",
    "PromptInjectionInspector",
    "ProviderGrouping",
    "RecoveryDecision",
    "RecoveryManager",
    "ResourceActivator",
    "ResourceDefinition",
    "ResourceKind",
    "ResourceLoadError",
    "ResourceMetadata",
    "ResourceNotFoundError",
    "ResourceRegistry",
    "ResourceStats",
    "ResourceValidationError",
    "Retriever",
    "RetryPolicy",
    "RouteDecision",
    "RoutingCase",
    "RoutingCaseStore",
    "RoutingDecision",
    "RuleBasedPlanner",
    "SafetyFinding",
    "SafetyInspector",
    "RuleBasedSetSelector",
    "SQLiteStateStore",
    "SQLiteConnector",
    "SearchQuery",
    "SearchResult",
    "SemanticVersion",
    "SecretRef",
    "SecretResolutionError",
    "SecretResolver",
    "ShellConnector",
    "SelectedResourceSet",
    "SelectionContext",
    "SelectionResult",
    "SetSelector",
    "StateConflictError",
    "StateEvent",
    "StateStore",
    "TaskNotFoundError",
    "TaskResult",
    "TaskState",
    "ToolCall",
    "ToolInputError",
    "ToolResult",
    "ToolRuntime",
    "ValidationIssue",
    "VersionRange",
    "build_package_lock",
    "compensation_for",
    "connect_mcp_server",
    "discover_package_roots",
    "estimate_tokens",
    "load_registry",
    "label_untrusted_content",
    "load_resource_definitions",
    "read_package_manifest",
    "mcp_tool_implementations",
    "mcp_tool_resources",
    "outcomes_from_audit",
    "resolve_case",
    "validate_arguments",
    "validate_plan",
    "tokenize",
    "connector_implementations",
    "connector_resources",
    "connector_tools",
    "install_connectors",
    "verify_local_package",
    "write_package_lock",
    "__version__",
]

from ._version import __version__
